#!/bin/bash

_PKI_DIR=/etc/salt/pki
_SALT_ROOTFILES=/srv
_CURRENT_DIR=$(pwd)
_EPEL_RELEASE=http://ftp.linux.ncsu.edu/pub/epel/6/i386/epel-release-6-8.noarch.rpm
_CONTROLLER_NAME=""
_EXTRA_PKGS="cpio net-snmp-utils"
_XCAT_INSTALLED=false

echo -e \\033ct clear
tput clear

echo -e "\n                   /\\___/\\"
echo -e "                   \\ -.- /"
echo -e "                   \`-.^.-'          **xCAT** "   
echo -e "                     /\"\  \n"
echo -e "“Cats are intended to teach us that not everything in nature has a purpose.” \n"

install_requirements(){

  yum install -y yum-utils
  yum install -y createrepo

} &> /dev/null

xcat_repo_add(){
  
  reposync --config=./xCAT-repo/xCAT-Core.repo --repoid=xcat-2-core --download_path=./xCAT-repo
  createrepo ./xCAT-repo/xcat-2-core

  reposync --config=./xCAT-repo/xCAT-Deps.repo --repoid=xcat-dep --download_path=./xCAT-repo
  createrepo ./xCAT-repo/xcat-dep

  rm -rf /etc/yum.repos.d/xCAT-Core.repo
  rm -rf /etc/yum.repos.d/xCAT-Deps.repo

	cat <<- EOF > /etc/yum.repos.d/xCAT-Core.repo
	[xcat-2-core-local]
	name=xCAT 2 Core packages
	baseurl=file:///root/salty/xCAT-repo/xcat-2-core
	enabled=1
	gpgcheck=1
	gpgkey=https://sourceforge.net/projects/xcat/files/yum/2.8/xcat-core/repodata/repomd.xml.key
	EOF

	cat <<- EOF > /etc/yum.repos.d/xCAT-Deps.repo
	[xcat-dep-local]
	name=xCAT 2 depedencies
	baseurl=file:///root/salty/xCAT-repo/xcat-dep
	enabled=1
	gpgcheck=1
	gpgkey=https://sourceforge.net/projects/xcat/files/yum/xcat-dep/rh6/x86_64/repodata/repomd.xml.key
	EOF

} &> /dev/null

xcat_cleanup(){
  
  # forced 'hard' re-install, will remove xCAT packages
  echo -e "Removing all xCAT config\n"

  rm -rf /install
  rm -rf /root/.xcat
  rm -rf /tftpboot
  rm -rf /etc/apache2/conf.d/xcat.conf
  rm -rf /etc/httpd/conf.d/xcat.conf
  rm -rf /etc/xCATMN
  rm -rf /opt/xcat/
  rm -rf /etc/xcat

  echo -e "Forcing removal of all xCAT packages from the YUM database:\n"
  for pkg in $(repoquery --requires --recursive --resolve --installed -i xCAT | grep "Name        :" | awk '{print $3}'); do
   echo -e "\e[31m[ Removing ]\e[0m $(seq -s. $(expr 60 - ${#pkg})|tr -d '[:digit:]') $pkg"
   rpm -e --justdb --nodeps $pkg
  done


}

xcat_install(){

  # 'light' re-install: will not remove the packages, just install over existing ones

  echo -e "\nInstalling necessary packages and creating new configuration files... (might take a while)\c"
  yum install -y $(repoquery --requires --resolve --recursive xCAT) $_EXTRA_PKGS #> /dev/null
  echo -e "\nDone!\n"

}

xcat_system_config(){

  #Network configuration

	cat <<- EOF > /etc/ntp.conf
	server 127.127.1.0
	fudge 127.127.1.0 stratum 10
	server 0.europe.pool.ntp.org iburst
	server 1.europe.pool.ntp.org iburst 
	server 2.europe.pool.ntp.org iburst
	server 3.europe.pool.ntp.org iburst
	driftfile /var/lib/ntp/drift
	EOF

	cat <<- EOF > /etc/sysconfig/network
	NETWORKING=yes
	HOSTNAME=controller
	EOF

	cat <<- EOF > /etc/hosts
	127.0.0.1	localhost
	10.141.255.254	controller controller.cluster
	EOF

	cat <<- EOF > /etc/sysconfig/network-scripts/ifcfg-eth0
	DEVICE=eth0
	ONBOOT=yes
	BOOTPROTO=static
	IPADDR=10.141.255.254
	PREFIX=16
	EOF

	cat <<- EOF > /etc/sysconfig/network-scripts/ifcfg-eth1
	DEVICE=eth1
	ONBOOT=yes
	BOOTPROTO=dhcp
	PEERDNS=no
	EOF

	cat <<- EOF > /etc/resolv.conf
	search cluster
	nameserver 10.141.255.254
	nameserver 8.8.8.8
	EOF

  hostname controller
  service network restart &> /dev/null

}

post_xcat_install(){

. /etc/profile.d/xcat.sh
echo -e "\nRestoring xCat tables: $(/opt/xcat/sbin/restorexCATdb -p ./tables)"
/opt/xcat/sbin/chtab netname=10_141_0_0-255_255_0_0 networks.dynamicrange=10.141.230.1-10.141.239.254
/opt/xcat/sbin/nodeadd node001-node004 groups=compute
/opt/xcat/sbin/makehosts
/opt/xcat/sbin/makedhcp -n
/opt/xcat/sbin/makedhcp -a
/opt/xcat/sbin/makedns -n

service dhcpd restart
service named restart

}

xcat_pre_install(){

  if [ -n "$(rpm -qa | grep xCAT)" ]; then
    echo -e "Found previous xCAT installation..."
    _XCAT_INSTALLED=true
  fi  

}

install_requirements
xcat_pre_install


if [ "$_XCAT_INSTALLED" = true ]; then
  xcat_cleanup
fi

xcat_install

xcat_system_config



