#!/bin/bash

_PKI_DIR=/etc/salt/pki
_SALT_ROOTFILES=/srv
_CURRENT_DIR=$(pwd)
_EPEL_RELEASE=http://ftp.linux.ncsu.edu/pub/epel/6/i386/epel-release-6-8.noarch.rpm
_CONTROLLER_NAME=""


echo -e "\n                   /\\___/\\"
echo -e "                   \\ -.- /"
echo -e "                   \`-.^.-'          **xCAT** "   
echo -e "                     /\"\  \n"
echo -e "“Cats are intended to teach us that not everything in nature has a purpose.” \n"


clean(){

  rm -rf /etc/yum.repos.d/xCAT*

}

xcat_setup(){

  #Add the xCAT repo to our repositories

printf %s "\
[xcat-2-core]
name=xCAT 2 Core packages
baseurl=https://sourceforge.net/projects/xcat/files/yum/2.8/xcat-core
enabled=1
gpgcheck=1
gpgkey=https://sourceforge.net/projects/xcat/files/yum/2.8/xcat-core/repodata/repomd.xml.key
" > /etc/yum.repos.d/xCAT-Core.repo

printf %s "\
[xcat-dep]
name=xCAT 2 depedencies
baseurl=https://sourceforge.net/projects/xcat/files/yum/xcat-dep/rh6/x86_64
enabled=1
gpgcheck=1
gpgkey=https://sourceforge.net/projects/xcat/files/yum/xcat-dep/rh6/x86_64/repodata/repomd.xml.key
" > /etc/yum.repos.d/xCAT-Deps.repo

  #Install xCAT
  yum install -y xCAT
}


clean
xcat_setup
