#!/bin/bash

_PKI_DIR=/etc/salt/pki
_SALT_ROOTFILES=/srv
_CURRENT_DIR=$(pwd)
_EPEL_RELEASE=http://ftp.linux.ncsu.edu/pub/epel/6/i386/epel-release-6-8.noarch.rpm
_CONTROLLER_NAME=""


echo -e "\n                   /\\___/\\"
echo -e "                   \\ -.- /"
echo -e "                   \`-.^.-'          **xCAT** "   
echo -e "                     /\"\  \n"
echo -e "“Cats are intended to teach us that not everything in nature has a purpose.” \n"

tools_setup(){

  yum install -y yum-utils

}

xcat_remove(){

  rm -rf /install
  rm -rf /root/.xcat
  rm -rf /tftpboot
  rm -rf /etc/apache2/conf.d/xcat.conf
  rm -rf /etc/httpd/conf.d/xcat.conf
  rm -rf /etc/xCATMN
  rm -rf /opt/xcat/
  rm -rf /etc/xcat

  for i in $(rpm -qa); do
    if [ "$(repoquery -i $i | grep Repository | awk '{print $3}')" == "xcat-2-core" ]; then
      echo $i
      yum reinstall -y "$(repoquery -i $i | grep Name | awk '{print $3}')"
      #rpm -e --nodeps "$(repoquery -i $i | grep Name | awk '{print $3}')"
    fi
    if [ "$(repoquery -i $i | grep Repository | awk '{print $3}')" == "xcat-dep" ]; then
      echo $i
      yum reinstall -y "$(repoquery -i $i | grep Name | awk '{print $3}')"
      #rpm -e --nodeps "$(repoquery -i $i | grep Name | awk '{print $3}')"
    fi
  done

  rm -rf /etc/yum.repos.d/xCAT*

}

xcat_install(){

  #Add the xCAT repo to our repositories:
	cat <<- EOF > /etc/yum.repos.d/xCAT-Core.repo
	[xcat-2-core]
	name=xCAT 2 Core packages
	baseurl=https://sourceforge.net/projects/xcat/files/yum/2.8/xcat-core
	enabled=1
	gpgcheck=1
	gpgkey=https://sourceforge.net/projects/xcat/files/yum/2.8/xcat-core/repodata/repomd.xml.key
	EOF

	cat <<- EOF > /etc/yum.repos.d/xCAT-Deps.repo
	[xcat-dep]
	name=xCAT 2 depedencies
	baseurl=https://sourceforge.net/projects/xcat/files/yum/xcat-dep/rh6/x86_64
	enabled=1
	gpgcheck=1
	gpgkey=https://sourceforge.net/projects/xcat/files/yum/xcat-dep/rh6/x86_64/repodata/repomd.xml.key
	EOF
  
yum install xCAT

}

if [ -n "$(rpm -qa | grep xCAT)" ]; then
  xcat_remove
fi

xcat_install


